import { ProvinciaDto } from "../Core/Model/ProvinciaDto";

export const PROVINCIAS: ProvinciaDto[] = [
  { id: 1, descripcion: 'Álava' },
  { id: 2, descripcion: 'Albacete' },
  { id: 3, descripcion: 'Alicante' },
  { id: 4, descripcion: 'Almería' },
  { id: 5, descripcion: 'Asturias' },
  { id: 6, descripcion: 'Ávila' },
  { id: 7, descripcion: 'Badajoz' },
  { id: 8, descripcion: 'Barcelona' },
  { id: 9, descripcion: 'Burgos' },
  { id: 10, descripcion: 'Cáceres' },
  { id: 11, descripcion: 'Cádiz' },
  { id: 12, descripcion: 'Cantabria' },
  { id: 13, descripcion: 'Castellón' },
  { id: 14, descripcion: 'Ciudad Real' },
  { id: 15, descripcion: 'Córdoba' },
  { id: 16, descripcion: 'Cuenca' },
  { id: 17, descripcion: 'Gerona' },
  { id: 18, descripcion: 'Granada' },
  { id: 19, descripcion: 'Guadalajara' },
  { id: 20, descripcion: 'Guipúzcoa' },
  { id: 21, descripcion: 'Huelva' },
  { id: 22, descripcion: 'Huesca' },
  { id: 23, descripcion: 'Islas Baleares' },
  { id: 24, descripcion: 'Jaén' },
  { id: 25, descripcion: 'La Coruña' },
  { id: 26, descripcion: 'La Rioja' },
  { id: 27, descripcion: 'Las Palmas' },
  { id: 28, descripcion: 'León' },
  { id: 29, descripcion: 'Lérida' },
  { id: 30, descripcion: 'Lugo' },
  { id: 31, descripcion: 'Madrid' },
  { id: 32, descripcion: 'Málaga' },
  { id: 33, descripcion: 'Murcia' },
  { id: 34, descripcion: 'Navarra' },
  { id: 35, descripcion: 'Orense' },
  { id: 36, descripcion: 'Palencia' },
  { id: 37, descripcion: 'Pontevedra' },
  { id: 38, descripcion: 'Salamanca' },
  { id: 39, descripcion: 'Santa Cruz de Tenerife' },
  { id: 40, descripcion: 'Segovia' },
  { id: 41, descripcion: 'Sevilla' },
  { id: 42, descripcion: 'Soria' },
  { id: 43, descripcion: 'Tarragona' },
  { id: 44, descripcion: 'Teruel' },
  { id: 45, descripcion: 'Toledo' },
  { id: 46, descripcion: 'Valencia' },
  { id: 47, descripcion: 'Valladolid' },
  { id: 48, descripcion: 'Vizcaya' },
  { id: 49, descripcion: 'Zamora' },
  { id: 50, descripcion: 'Zaragoza' }
];
